title: "ノーコードWebサイト制作ツール STUDIO超入門（執筆途中）"
summary: "STUDIOの操作方法を、テキストと画像と動画で解説します。「手を動かして覚える派」におすすめ。STUDIOはアップデートが早いので、ここに書かれている内容はすでに古くなっている可能性があります。なお、5/20にSTUDIO 4.0が発表される予定があり、その時点で多少なりとも確実に古くなる予定です。あらかじめご了承ください。"
topics: ["STUDIO","nocode"]
published: true
price: 0 # 有料の場合200〜5000
toc_depth: 2
# 本に含めるチャプターを順番に並べましょう
chapters:
  - first
  - pricing
  - join
  - dashboard
  - grasp-editor
  - edit-image
  - edit-text
  # - edit-cms
  #- change-text-design
